### ISSUE TITLE
Token-based authentication appears to not be working

### ISSUE THREAD

**Issue by PaulFurtado** [harbur/kubernetic-issues#16] opened 2017-03-03 20:36 UTC
kubectl works fine, my ~/.kube/config is set up as:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: <redacted>
  name: iad03
contexts:
- context:
    cluster: iad03
    user: test-admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: test-admin
  user:
    token: <redacted>
```
in the console, I see:
![screenshot from 2017-03-03 15-33-07](https://cloud.githubusercontent.com/assets/704936/23568087/1592b4fc-0027-11e7-87b9-69a8515dc5d7.png)

It's not clear that it's sending the Authorization header along to the server at all. Am I doing anything wrong here?

**Comment by PaulFurtado** [comment] 2017-03-03 20:39
Also, forgot to mention, that I use kubectl all day and it works fine. The official kubernetes python client library also has no trouble with this kube config file either

**Comment by spiddy** [comment] 2017-03-03 21:03
This is duplicate of #7.

Next release fixes this issue.

**Comment by PaulFurtado** [comment] 2017-03-03 21:08
Thanks for the quick response, sounds good. We look forward to trying this out!

**Comment by spiddy** [comment] 2017-03-09 16:41
Token-based authentication is added in v0.7.0

**Comment by PaulFurtado** [comment] 2017-03-23 19:06
Hey @spiddy just tried and this actually is still not fixed. 

To talk to the kube API using the token in the example YAML config I showed above, all that needs to happen is for you to send the `Authorization` header with the value `Bearer <token>` with each request.

**Comment by spiddy** [comment] 2017-03-24 11:25
You're right the `user.token` option is not supported yet.

I can't find a decent documentation for the available formats of kubectl authentications, so in Wiki I collected some examples of available formats (https://github.com/harbur/kubernetic-issues/wiki) for reference.

No cloud provider though provides tokens directly, am I missing a use case? Certainly the tokens can be used from ServiceAccounts for example, what is your situation?

This logic (read kubeconfig) should probably pushed upstream to https://github.com/Goyoo/node-k8s-client.

**Comment by alexouzounis** [comment] 2017-03-24 11:31
Our setup uses tokens to authenticate to the api server which in turn is behind a private elb in a private vpc. Whitelisted users do an ssh tunnel via the bastion host and use kubectl like so to interact with the cluster:
```
    ${kubectl_exec} config set-cluster ${k8s_cluster_name} --server=${protocol}://localhost:${local_port} --certificate-authority=${ca_cert} --embed-certs=true
    ${kubectl_exec} config set-credentials ${KUBE_APISERVER_USERNAME} --token ${KUBE_APISERVER_TOKEN}
    ${kubectl_exec} config set-context ${USER}-${k8s_cluster_name} --cluster=${k8s_cluster_name} --user=${KUBE_APISERVER_USERNAME}
    ${kubectl_exec} config use-context ${USER}-${k8s_cluster_name}
```

not sure why this method of authenticating is considered special. We would love to use your software and purchase enterprise licenses but assuming we get it to work :)
https://github.com/Goyoo/node-k8s-client Appears to support token based authentication - Am i missing something here ?

**Comment by alexouzounis** [comment] 2017-03-24 11:32
This appears similar to #7 and #24

**Comment by spiddy** [comment] 2017-03-24 11:35
It supports token based, there is no wiring yet to get the data from the ~/.kube/config and pass it to the k8s client. (The client supports reading ~/.kube/config only when `kubectl` binary is used which is not in this case)

**Comment by spiddy** [comment] 2017-03-24 11:35
Working on it

**Comment by spiddy** [comment] 2017-05-01 09:40
Another take on token-based authentication (v0.8.0).

Please reopen if it still persists.

**Closed by spiddy** 2017-05-01 09:40 UTC
